### ISSUE TITLE
Version 1.10.1 contains incorrect VERSION value in Makefile

### ISSUE THREAD

**Issue by imincik** [linz/linz-bde-schema#193]
In Makefile we have:

```
VERSION=1.10.0
```

**Comment by strk** [comment]
For some reason this ticket is not being closed by the `closes #193` text in the log of the commit now merged to `release-0.10` branch: https://github.com/linz/linz-bde-schema/commit/8598156f19b5589ea965ad0dfadf610fa9033430

**Comment by strk** [comment]
I'm closing manually, but it would be interesting to know WHY it did not work automatically

**Comment by strk** [comment]
Version 1.10.2 [tagged](https://github.com/linz/linz-bde-schema/releases/tag/1.10.2) and [packaged](https://packagecloud.io/linz/test/packages/ubuntu/bionic/linz-bde-schema_1.10.2-linz~bionic1_all.deb)

NOTE: since the linz-software-repository action does NOT commit debian/changelog back to branch, this new release will likely be missing changes of 1.10.1 in its debian/changelog

**Comment by strk** [comment]
Let's discuss the limitations of linz-software-repository action in https://github.com/linz/linz-software-repository/issues/29
