### ISSUE TITLE
Tag '1.12.0' is missing in git repository

### ISSUE THREAD

**Issue by imincik** [linz/linz-bde-schema#204]
Tag `1.12.0` is missing in git repository. I can only see `1.12-start` .

**Comment by strk** [comment]
This is intentional: the tag `1.12-start` represents the start of the
work that will end up being `1.12.0` (thus not existant yet).

**Comment by imincik** [comment]
@strk , we already have https://packagecloud.io/linz/test/packages/ubuntu/bionic/linz-bde-schema_1.12-start-linz~bionic_all.deb in repository, so version `1.12` should be already released and tag present.

**Comment by imincik** [comment]
Also, if creating `<TAG>-start` is some packaging workaround it doesn't look as good way to go to me.

**Comment by strk** [comment]
Yes, `<BRANCH>-start1 is an automated packaging workaround. It serves the purpose of indicating the first commit drifting from last stable release. The goal is to have the packages from master branch be always ahead of those from stable branches.
There is no `1.12.0` tag because `1.12.0` was not released. In debian terms `1.12-start` is lower than `1.12.0` so when `1.12.0` will be released the upgrade procedures will upgrade from `1.12-start`, if it was ever installed.

**Comment by strk** [comment]
I've now released 1.12.0 to fix this problem, I'm still dealing with pacakges as v4 (and v5) of linz-software-repository is fragile and failed to push changes/tags back to repository because no remote branch pointed at the built reference (I probably pushed an additional commit to master branch before CI completed, which made the master branch _contain_ but not _point_at_ the commit). I guess I should make linz-software-repository fail in those cases.

**Comment by strk** [comment]
Packages and git changes are ready now
